push = require 'lib/push'
Class = require 'lib/class'
require 'src/constants'
require 'src/Human'
require 'src/Zombie'
require 'src/StateMachine'
require 'src/states/BaseState'
require 'src/states/StartState'
require 'src/states/PlayState'